# Generated by Django 3.1.2 on 2020-10-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
